### ISSUE TITLE
Allow the user to pick the version of optifine to install if multiple versions are detected

### ISSUE THREAD

**Issue by SystemlessDev** [HyperiumClient/Installer#13]
Hyperium supports both I7 and Lx as of 15th of November 2019. Removing I7 compatibility would be both stupid and unnecessary since I7 will probably be continued to be used for a long time. Allowing the user to choose between Lx and I7 if both of them gets detected would be a good idea in case something goes wrong between Hyperium and one of the versions.

**Comment by ChachyDev** [comment]
hyperium-installer --optifine --inject "/home/chachy/Downloads/Optifine-1.8.9-I7.jar"

**Comment by SystemlessDev** [comment]
It would be ten times better with a gui for this. Making a user use the terminal is a bad idea

**Comment by ChachyDev** [comment]
i mean for the cli kids

**Comment by myerDOT** [comment]
In chachy’s defense, anyone who cares about what Optifine version he/she is using is probably comfortable with using a terminal.
Then again, it would be much more accessible for people to use the GUI.
If this feature is added, make it a GUI function.

**Comment by GamingGeek** [comment]
@MyerFire They may need to install an older version, e.g. I7 if they're experiencing issues with the preview versions and currently the only way to do that is to uninstall the preview version and reinstall Hyperium

**Comment by ChachyDev** [comment]
what about the people who want to use cli then, because right now you are saying "haha we are adobe who cares about supporting that/that feature for you"

**Comment by myerDOT** [comment]
Just add both.
Satisfy both sides. Not a big deal.

**Comment by GamingGeek** [comment]
Nobody said both wouldn't be added...

**Comment by myerDOT** [comment]
Then what are we even going on about..?

**Comment by ChachyDev** [comment]
i mean i did say "for the cli kids"

**Comment by ghost** [comment]
talk about this on discord rather than flooding the issue and webhooks channel

**Comment by ChachyDev** [comment]
Ok Asbyth
