### ISSUE TITLE
Installer freezes if the user is too quick when they install optifine

### ISSUE THREAD

**Issue by SystemlessDev** [HyperiumClient/Installer#17]
The installer decides to freeze if you click next after you've installed optifine.
Steps to reproduce:
1 - Mark optifine as an addon
2 - Press next and install optifine
3 - Press next as soon as the optifine installer exited
4 - Installer gets stuck on ![this](https://user-images.githubusercontent.com/45434286/71648255-b0f12680-2d02-11ea-9b56-b06070be461e.png)

**Comment by ghost** [comment]
literally how

**Comment by GamingGeek** [comment]
h o w

**Comment by SystemlessDev** [comment]
It skips past the this page
![image](https://user-images.githubusercontent.com/45434286/71648271-eac22d00-2d02-11ea-9696-b83121b44bc1.png)
