### ISSUE TITLE
Installer issues / requested features

### ISSUE THREAD

**Issue by SystemlessDev** [HyperiumClient/Installer#2]
- Does not check for Optifine I7 specifically (hyperium crashes with any other version)
- CLI mode does not error out when optifine I7 isn't installed
- Check for installed addons and make them checked in the installer + add the ability to remove them via the installer
- MultiMC support

**Comment by Cubxity** [comment]
Can you put these in separate issues?

**Comment by SystemlessDev** [comment]
i hate you
