### ISSUE TITLE
Claims JavaFX not installed despite installing openjfx using apt (Ubuntu 19.10)

### ISSUE THREAD

**Issue by Alex-Programs** [HyperiumClient/Installer#30]

**Comment by lyndseyy** [comment]
Open a terminal/command prompt window and type java -jar  (with a space after it), drag the hyperium installer onto the window and if you want optifine, you'll need to download it from https://optifine.net/downloads (1.8.9) and then after the text it fills in from dragging the installer onto the window, add  --optifine --optifinePath  and then drag the optifine file ontothe window. Once you've done all that, hit enter.

It should look like java -jar "path/to/hyperium.jar" --optifine --optifinePath "path/to/optifine.jar"

**Comment by SystemlessDev** [comment]
And there is another solution if you **really** want to get the GUI working. You have to make sure that you're using OpenJDK 8, and you have to do [this](https://stackoverflow.com/a/56166582) to install OpenJFX. You have to use older versions of the OpenJFX packages due to how Ubuntu set up their packages.

**Comment by Alex-Programs** [comment]
I have a new problem when I try to start it from the minecraft launcher - "An unexpected issue has occurred and the game has crashed." However, the installer worked fine and I learnt something new (that you could drag stuff into the terminal.) Thanks for the help.

**Comment by SystemlessDev** [comment]
This would be because you're using Java 11 to launch hyperium. Set your default jre to Java 8 or set it as Java 8 in the Minecraft launcher.
