### ISSUE TITLE
Fails with generic error message

### ISSUE THREAD

**Issue by Alex-Programs** [HyperiumClient/Installer#31]
Older versions of minecraft, including hyperium, crash when I try to open them in the minecraft launcher on Linux. The error message is a generic "Unexpected error, sorry for the inconvenience."

I have read through the logs and can't see anything obvious. 
[launcher_log.txt](https://github.com/HyperiumClient/Installer/files/4485773/launcher_log.txt)

**Comment by ChachyDev** [comment]
Are you using Java 11, the same for the openjfx version?

**Comment by Alex-Programs** [comment]
openjdk 11.0.6 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10-post-Ubuntu-1ubuntu119.10.1)
OpenJDK 64-Bit Server VM (build 11.0.6+10-post-Ubuntu-1ubuntu119.10.1, mixed mode, sharing)

I can't find my openJFX version because my $JAVA_HOME is blank.

**Comment by ChachyDev** [comment]
Remove the java package and install `openjdk-8-jre` and run `apt purge openjfx
apt install openjfx=8u161-b12-1ubuntu2 libopenjfx-jni=8u161-b12-1ubuntu2 libopenjfx-java=8u161-b12-1ubuntu2
apt-mark hold openjfx libopenjfx-jni libopenjfx-java`

**Comment by SystemlessDev** [comment]
This would've been solved with a quick Google search. It isn't related to the installer nor hyperium itself. Please set the default system Java to openjdk 8, or manually path Minecraft to use openjdk 8.
