### ISSUE TITLE
Running on Linux w/ JavaFX Issues

### ISSUE THREAD

**Issue by JPeisach** [HyperiumClient/Installer#32]
Three java's are installed: 14, 11 for JRE and 8

Gradle build succeeds-but running in jar or running any tests results of a big crashdump.

Gradle 6.3. JavaFX even when using the predownloaded version

In: :compileKotlin

**Comment by myerDOT** [comment]
Are you sure you are using Java 8 for everything?

**Comment by JPeisach** [comment]
Yes- I run the jar with JRE 8 Runtime. I'm sure and HOPE that gradle uses java 8 by default but it probably doesn't so i'll have to see
________________________________

**Comment by myerDOT** [comment]
OpenJDK does not contain JavaFX, so you will either need to use Oracle Java or download OpenJFX.
Also, please join our [Discord](https://discord.gg/sk1er) for faster support.

**Comment by ChachyDev** [comment]
how
