### ISSUE TITLE
Add the ability for us to disable addons remotely

### ISSUE THREAD

**Issue by SystemlessDev** [HyperiumClient/Installer#8]
![image](https://user-images.githubusercontent.com/45434286/68088787-bd701480-fe62-11e9-8a26-30b1ee16250b.png)
![image](https://user-images.githubusercontent.com/45434286/68088788-c1039b80-fe62-11e9-9ec9-7002e10fd05f.png)

Said file is located here:
https://github.com/HyperiumClient/Hyperium-Repo/blob/master/installer/addons.json

**Comment by ghost** [comment]
Done in https://github.com/HyperiumClient/Installer/commit/f7611ecf27bef2a438fdff0e8349d998652ef8cd
